/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import database.koneksi;
import javax.swing.JOptionPane;
//prepare statement
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class frameHasil extends javax.swing.JFrame {
    
    koneksi obj; 
    
    public DefaultTableModel modelTabelHasil;

    /**
     * Creates new form frameHasil
     */
    public frameHasil() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        modelTabelHasil = new DefaultTableModel();
        tabelHasil.setModel(modelTabelHasil);
        modelTabelHasil.addColumn("ID HASIL");
        modelTabelHasil.addColumn("TANGGAL");
        modelTabelHasil.addColumn("KODE PENYAKIT");
        modelTabelHasil.addColumn("KODE GEJALA");
        modelTabelHasil.addColumn("ID");
        modelTabelHasil.addColumn("HASIL NILAI");
        modelTabelHasil.addColumn("USER");
        tampilDataHasil();
    }
    
    
    public void tampilDataHasil() {
        try {
            modelTabelHasil.getDataVector().removeAllElements();
            modelTabelHasil.fireTableDataChanged();
            
            PreparedStatement query = obj.konek.prepareStatement("SELECT * FROM hasil");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] line = new Object[7];
                line[0] = data.getString("id_hasil");
                line[1] = data.getString("tanggal");
                line[2] = data.getString("kode_penyakit");
                line[3] = data.getString("kode_gejala");
                line[4] = data.getString("id");
                line[5] = data.getString("hasil_nilai");
                line[6] = data.getString("user");
                modelTabelHasil.addRow(line);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdHasil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTgl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKdPenyakit = new javax.swing.JTextField();
        txtKdGejala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHasilNilai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHasil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id Hasil");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Kode Penyakit");

        jLabel4.setText("Kode Gejala");

        jLabel5.setText("Id");

        jLabel6.setText("Hasil Nilai");

        jLabel7.setText("User");

        jButton1.setText("Simpan Statment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan Prepare Statement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelHasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHasilNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKdGejala, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKdGejala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHasilNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
           if (txtIdHasil.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Id Hasil belum di isi");
               txtIdHasil.requestFocus();
           } else if (txtTgl.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Tanggal belum diisi");
               txtTgl.requestFocus();
           } else if (txtKdPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Penyakit belum diisi");
               txtKdPenyakit.requestFocus();
           } else if (txtKdGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Gejala belum diisi");
               txtKdGejala.requestFocus();
           } else if (txtId.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "ID belum diisi");
               txtId.requestFocus();
           } else if (txtHasilNilai.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Hasil Nilai Nilai belum diisi");
               txtHasilNilai.requestFocus();
           } else if (txtUser.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "User belum diisi");
               txtUser.requestFocus();
           } else {
               String sql = "insert into hasil value('"+txtIdHasil.getText()+"','"+txtTgl.getText()+"','"+txtKdPenyakit.getText()+"','"+txtKdGejala.getText()+"','"+txtId.getText()+"','"+txtHasilNilai.getText()+"','"+txtUser.getText()+"')";
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
           if (txtIdHasil.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Id Hasil belum di isi");
               txtIdHasil.requestFocus();
           } else if (txtTgl.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Tanggal belum diisi");
               txtTgl.requestFocus();
           } else if (txtKdPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Penyakit belum diisi");
               txtKdPenyakit.requestFocus();
           } else if (txtKdGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Gejala belum diisi");
               txtKdGejala.requestFocus();
           } else if (txtId.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "ID belum diisi");
               txtId.requestFocus();
           } else if (txtHasilNilai.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Hasil Nilai Nilai belum diisi");
               txtHasilNilai.requestFocus();
           } else if (txtUser.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "User belum diisi");
               txtUser.requestFocus();
           } else {
               String sqlCari = "SELECT * FROM hasil WHERE id_hasil ='"+txtIdHasil.getText()+"'";
               ResultSet cari = obj.konek.createStatement().executeQuery(sqlCari);
               if (cari.next()){
                    JOptionPane.showMessageDialog(this, "ID Hasil Sudah Terdaftar");
                         txtTgl.setText(cari.getString(2));
                         txtKdPenyakit.setText(cari.getString(3));
                         txtKdGejala.setText(cari.getString(4));
                         txtId.setText(cari.getString(5));
                         txtHasilNilai.setText(cari.getString(6));
                         txtUser.setText(cari.getString(7));
               } else {
                    String sql = "INSERT INTO hasil VALUE(?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement simpan = obj.konek.prepareStatement(sql);
                    simpan.setString(1, txtIdHasil.getText());
                    simpan.setString(2, txtTgl.getText());
                    simpan.setString(3, txtKdPenyakit.getText());
                    simpan.setString(4, txtKdGejala.getText());
                    simpan.setString(5, txtId.getText());
                    simpan.setString(6, txtHasilNilai.getText());
                    simpan.setString(7, txtUser.getText());
                    simpan.executeUpdate();
                    tampilDataHasil();
                    
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
               }
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelHasilMouseClicked
        // TODO add your handling code here:
        int baris = tabelHasil.getSelectedRow();
        String id_hasil = tabelHasil.getValueAt(baris, 0).toString();
        String tanggal = tabelHasil.getValueAt(baris, 1).toString();
        String kode_penyakit = tabelHasil.getValueAt(baris, 2).toString();
        String kode_gejala = tabelHasil.getValueAt(baris, 3).toString();
        String id = tabelHasil.getValueAt(baris, 4).toString();
        String hasil_nilai = tabelHasil.getValueAt(baris, 5).toString();
        String user = tabelHasil.getValueAt(baris, 6).toString();
        txtIdHasil.setText(id_hasil);
        txtTgl.setText(tanggal);
        txtKdPenyakit.setText(kode_penyakit);
        txtKdGejala.setText(kode_gejala);
        txtId.setText(id);
        txtHasilNilai.setText(hasil_nilai);
        txtUser.setText(user);
    }//GEN-LAST:event_tabelHasilMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
            if (
                    (txtIdHasil.getText().isEmpty()) &&
                    (txtTgl.getText().isEmpty()) &&
                    (txtKdPenyakit.getText().isEmpty()) &&
                    (txtKdGejala.getText().isEmpty()) &&
                    (txtId.getText().isEmpty()) &&
                    (txtHasilNilai.getText().isEmpty())&&
                    (txtUser.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE hasil SET tanggal=?, kode_penyakit=?, kode_gejala=?, id=?, hasil_nilai=?, user=?  WHERE id_hasil=?";
                PreparedStatement ubah = obj.konek.prepareStatement(sql);
                ubah.setString(1, txtTgl.getText());
                ubah.setString(2, txtKdPenyakit.getText());
                ubah.setString(3, txtKdGejala.getText());
                ubah.setString(4, txtId.getText());
                ubah.setString(5, txtHasilNilai.getText());
                ubah.setString(6, txtUser.getText());
                ubah.setString(7, txtIdHasil.getText());
                ubah.executeUpdate();
                tampilDataHasil();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try {
            if (
                    (txtIdHasil.getText().isEmpty()) &&
                    (txtTgl.getText().isEmpty()) &&
                    (txtKdPenyakit.getText().isEmpty()) &&
                    (txtKdGejala.getText().isEmpty()) &&
                    (txtId.getText().isEmpty()) &&
                    (txtHasilNilai.getText().isEmpty())&&
                    (txtUser.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM hasil WHERE id_hasil=?";
                PreparedStatement hapus = obj.konek.prepareStatement(sql);
                hapus.setString(1, txtIdHasil.getText());
                hapus.executeUpdate();
                tampilDataHasil();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameHasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelHasil;
    private javax.swing.JTextField txtHasilNilai;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdHasil;
    private javax.swing.JTextField txtKdGejala;
    private javax.swing.JTextField txtKdPenyakit;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
