/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import database.koneksi;
import javax.swing.JOptionPane;
//prepare statement
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class framePenyakit extends javax.swing.JFrame {
    
    koneksi obj;
    
    public DefaultTableModel modelTabelPenyakit;

    /**
     * Creates new form framePenyakit
     */
    public framePenyakit() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        modelTabelPenyakit = new DefaultTableModel();
        tabelPenyakit.setModel(modelTabelPenyakit);
        modelTabelPenyakit.addColumn("KODE PENYAKIT");
        modelTabelPenyakit.addColumn("NAMA PENYAKIT");
        modelTabelPenyakit.addColumn("DETAIL PENYAKIT");
        modelTabelPenyakit.addColumn("SARAN");
        modelTabelPenyakit.addColumn("GAMBAR");
        tampilDataPenyakit();
    }
    
    
    
    public void tampilDataPenyakit() {
        try {
            modelTabelPenyakit.getDataVector().removeAllElements();
            modelTabelPenyakit.fireTableDataChanged();
            
            PreparedStatement query = obj.konek.prepareStatement("SELECT * FROM penyakit");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] line = new Object[5];
                line[0] = data.getString("kode_penyakit");
                line[1] = data.getString("nama_penyakit");
                line[2] = data.getString("detail_penyakit");
                line[3] = data.getString("saran");
                line[4] = data.getString("gambar");
                modelTabelPenyakit.addRow(line);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKdPenyakit = new javax.swing.JTextField();
        txtNmPenyakit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDetailPenyakit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSaran = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGambar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenyakit = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Penyakit");

        jLabel2.setText("Nama Penyakit");

        jLabel3.setText("Detail Penyakit");

        jLabel4.setText("Saran");

        jLabel5.setText("Gambar");

        jButton1.setText("Simpan Statement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelPenyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPenyakit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPenyakitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPenyakit);

        jButton2.setText("Simpan Prepare Statment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(79, 79, 79)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNmPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addComponent(txtDetailPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaran, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNmPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDetailPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        try {
           if (txtKdPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Penyakit belum di isi");
               txtKdPenyakit.requestFocus();
           } else if (txtNmPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Penyakit belum diisi");
               txtNmPenyakit.requestFocus();
           } else if (txtDetailPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Detail Penyakit belum diisi");
               txtDetailPenyakit.requestFocus();
           } else if (txtSaran.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Saran belum diisi");
               txtSaran.requestFocus();
           } else if (txtGambar.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Gambar belum diisi");
               txtGambar.requestFocus();
           } else {
               String sql = "insert into penyakit value('"+txtKdPenyakit.getText()+"','"+txtNmPenyakit.getText()+"','"+txtDetailPenyakit.getText()+"','"+txtSaran.getText()+"','"+txtGambar.getText()+"')";
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelPenyakitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPenyakitMouseClicked
        // TODO add your handling code here:
        int baris = tabelPenyakit.getSelectedRow();
        String kode_penyakit = tabelPenyakit.getValueAt(baris, 0).toString();
        String nama_penyakit = tabelPenyakit.getValueAt(baris, 1).toString();
        String detail_penyakit = tabelPenyakit.getValueAt(baris, 2).toString();
        String saran = tabelPenyakit.getValueAt(baris, 3).toString();
        String gambar = tabelPenyakit.getValueAt(baris, 4).toString();
        txtKdPenyakit.setText(kode_penyakit);
        txtNmPenyakit.setText(nama_penyakit);
        txtDetailPenyakit.setText(detail_penyakit);
        txtSaran.setText(saran);
        txtGambar.setText(gambar);
    }//GEN-LAST:event_tabelPenyakitMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
           if (txtKdPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Penyakit belum di isi");
               txtKdPenyakit.requestFocus();
           } else if (txtNmPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Penyakit belum diisi");
               txtNmPenyakit.requestFocus();
           } else if (txtDetailPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Detail Penyakit belum diisi");
               txtDetailPenyakit.requestFocus();
           } else if (txtSaran.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Saran belum diisi");
               txtSaran.requestFocus();
           } else if (txtGambar.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Gambar belum diisi");
               txtGambar.requestFocus();
           } else {
               String sqlCari = "SELECT * FROM penyakit WHERE kode_penyakit ='"+txtKdPenyakit.getText()+"'";
               ResultSet cari = obj.konek.createStatement().executeQuery(sqlCari);
               if (cari.next()){
                    JOptionPane.showMessageDialog(this, "Kode Penyakit Sudah Terdaftar");
                         txtNmPenyakit.setText(cari.getString(2));
                         txtDetailPenyakit.setText(cari.getString(3));
                         txtSaran.setText(cari.getString(4));
                         txtGambar.setText(cari.getString(5));
               } else {
                    String sql = "INSERT INTO penyakit VALUE(?, ?, ?, ?, ?)";
                    PreparedStatement simpan = obj.konek.prepareStatement(sql);
                    simpan.setString(1, txtKdPenyakit.getText());
                    simpan.setString(2, txtNmPenyakit.getText());
                    simpan.setString(3, txtDetailPenyakit.getText());
                    simpan.setString(4, txtSaran.getText());
                    simpan.setString(5, txtGambar.getText());
                    simpan.executeUpdate();
                    tampilDataPenyakit();
                    
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
               }
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
            if (
                    (txtKdPenyakit.getText().isEmpty()) &&
                    (txtNmPenyakit.getText().isEmpty()) &&
                    (txtDetailPenyakit.getText().isEmpty()) &&
                    (txtSaran.getText().isEmpty()) &&
                    (txtGambar.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE penyakit SET nama_penyakit=?, detail_penyakit=?, saran=?, gambar=?  WHERE kode_penyakit=?";
                PreparedStatement ubah = obj.konek.prepareStatement(sql);
                ubah.setString(1, txtNmPenyakit.getText());
                ubah.setString(2, txtDetailPenyakit.getText());
                ubah.setString(3, txtSaran.getText());
                ubah.setString(4, txtGambar.getText());
                ubah.setString(5, txtKdPenyakit.getText());
                ubah.executeUpdate();
                tampilDataPenyakit();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try {
            if (
                    (txtKdPenyakit.getText().isEmpty()) &&
                    (txtNmPenyakit.getText().isEmpty()) &&
                    (txtDetailPenyakit.getText().isEmpty()) &&
                    (txtSaran.getText().isEmpty()) &&
                    (txtGambar.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM penyakit WHERE kode_penyakit=?";
                PreparedStatement hapus = obj.konek.prepareStatement(sql);
                hapus.setString(1, txtKdPenyakit.getText());
                hapus.executeUpdate();
                tampilDataPenyakit();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePenyakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePenyakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPenyakit;
    private javax.swing.JTextField txtDetailPenyakit;
    private javax.swing.JTextField txtGambar;
    private javax.swing.JTextField txtKdPenyakit;
    private javax.swing.JTextField txtNmPenyakit;
    private javax.swing.JTextField txtSaran;
    // End of variables declaration//GEN-END:variables
}
