/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import database.koneksi;
import javax.swing.JOptionPane;
//prepare statement
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class frameGejala extends javax.swing.JFrame {
    
    koneksi obj;    
    
    public DefaultTableModel modelTabelGejala;

    /**
     * Creates new form frameGejala
     */
    public frameGejala() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        modelTabelGejala = new DefaultTableModel();
        tabelGejala.setModel(modelTabelGejala);
        modelTabelGejala.addColumn("KODE GEJALA");
        modelTabelGejala.addColumn("NAMA GEJALA");
        modelTabelGejala.addColumn("KODE KATEGORI");
        modelTabelGejala.addColumn("ID KONDISI");
        tampilDataGejala();
    }
    
    
    public void tampilDataGejala() {
        try {
            modelTabelGejala.getDataVector().removeAllElements();
            modelTabelGejala.fireTableDataChanged();
            
            PreparedStatement query = obj.konek.prepareStatement("SELECT * FROM gejala");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[4];
                baris[0] = data.getString("kode_gejala");
                baris[1] = data.getString("nama_gejala");
                baris[2] = data.getString("kd_kategori");
                baris[3] = data.getString("id_kondisi");
                modelTabelGejala.addRow(baris);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKdGejala = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNmGejala = new javax.swing.JTextField();
        txtKdKategori = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdKondisi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGejala = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Gejala");

        jLabel2.setText("Nama Gejala");

        jLabel3.setText("Kode Kategori");

        jLabel4.setText("Id Kondisi");

        jButton1.setText("Simpan Statement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan Prepare Statement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelGejala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelGejala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGejalaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelGejala);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKdGejala, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNmGejala, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKdGejala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNmGejala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
           if (txtKdGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Gejala belum di isi");
               txtKdGejala.requestFocus();
           } else if (txtNmGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Nama Gejala belum diisi");
               txtNmGejala.requestFocus();
           } else if (txtKdKategori.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Kategori belum diisi");
               txtKdKategori.requestFocus();
           } else if (txtIdKondisi.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Id Kondisi belum diisi");
               txtIdKondisi.requestFocus();
           } else {
               String sql = "insert into gejala value('"+txtKdGejala.getText()+"','"+txtNmGejala.getText()+"','"+txtKdKategori.getText()+"','"+txtIdKondisi.getText()+"')";
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
           if (txtKdGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Gejala belum di isi");
               txtKdGejala.requestFocus();
           } else if (txtNmGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Nama Gejala belum diisi");
               txtNmGejala.requestFocus();
           } else if (txtKdKategori.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode Kategori belum diisi");
               txtKdKategori.requestFocus();
           } else if (txtIdKondisi.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Id Kondisi belum diisi");
               txtIdKondisi.requestFocus();
           } else {
               String sqlCari = "SELECT * FROM gejala WHERE kode_gejala ='"+txtKdGejala.getText()+"'";
               ResultSet cari = obj.konek.createStatement().executeQuery(sqlCari);
               if (cari.next()){
                    JOptionPane.showMessageDialog(this, "Kode Gejala Sudah Terdaftar");
                         txtNmGejala.setText(cari.getString(2));
                         txtKdKategori.setText(cari.getString(3));
                         txtIdKondisi.setText(cari.getString(4));
               } else {
                    String sql = "INSERT INTO gejala VALUE(?, ?, ?, ?)";
                    PreparedStatement simpan = obj.konek.prepareStatement(sql);
                    simpan.setString(1, txtKdGejala.getText());
                    simpan.setString(2, txtNmGejala.getText());
                    simpan.setString(3, txtKdKategori.getText());
                    simpan.setString(4, txtIdKondisi.getText());
                    simpan.executeUpdate();
                    tampilDataGejala();
                    
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
               }
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelGejalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGejalaMouseClicked
        // TODO add your handling code here:
     
        int baris = tabelGejala.getSelectedRow();
        String kode_gejala = tabelGejala.getValueAt(baris, 0).toString();
        String nama_gejala = tabelGejala.getValueAt(baris, 1).toString();
        String kd_kategori = tabelGejala.getValueAt(baris, 2).toString();
        String id_kondisi = tabelGejala.getValueAt(baris, 3).toString();
        txtKdGejala.setText(kode_gejala);
        txtNmGejala.setText(nama_gejala);
        txtKdKategori.setText(kd_kategori);
        txtIdKondisi.setText(id_kondisi);
    }//GEN-LAST:event_tabelGejalaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
            if (
                    (txtKdGejala.getText().isEmpty()) &&
                    (txtNmGejala.getText().isEmpty()) &&
                    (txtKdKategori.getText().isEmpty()) &&
                    (txtIdKondisi.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE gejala SET nama_gejala=?, kd_kategori=?, id_kondisi=?  WHERE kode_gejala=?";
                PreparedStatement ubah = obj.konek.prepareStatement(sql);
                ubah.setString(1, txtNmGejala.getText());
                ubah.setString(2, txtKdKategori.getText());
                ubah.setString(3, txtIdKondisi.getText());
                ubah.setString(4, txtKdGejala.getText());
                ubah.executeUpdate();
                tampilDataGejala();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try {
            if (
                    (txtKdGejala.getText().isEmpty()) &&
                    (txtNmGejala.getText().isEmpty()) &&
                    (txtKdKategori.getText().isEmpty()) &&
                    (txtIdKondisi.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM gejala WHERE kode_gejala=?";
                PreparedStatement hapus = obj.konek.prepareStatement(sql);
                hapus.setString(1, txtKdGejala.getText());
                hapus.executeUpdate();
                tampilDataGejala();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameGejala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameGejala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameGejala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameGejala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameGejala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelGejala;
    private javax.swing.JTextField txtIdKondisi;
    private javax.swing.JTextField txtKdGejala;
    private javax.swing.JTextField txtKdKategori;
    private javax.swing.JTextField txtNmGejala;
    // End of variables declaration//GEN-END:variables
}
