/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import database.koneksi;
import javax.swing.JOptionPane;
//prepare statement
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class frameBasisPengetahuan extends javax.swing.JFrame {
    
    koneksi obj;  
    
    public DefaultTableModel modelTabelBasisPengetahuan;

    /**
     * Creates new form frameBasisPengetahuan
     */
    public frameBasisPengetahuan() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        modelTabelBasisPengetahuan = new DefaultTableModel();
        tableBasisPengetahuan.setModel(modelTabelBasisPengetahuan);
        modelTabelBasisPengetahuan.addColumn("KODE PENGETAHUAN");
        modelTabelBasisPengetahuan.addColumn("KODE PENYAKIT");
        modelTabelBasisPengetahuan.addColumn("KODE GEJALA");
        modelTabelBasisPengetahuan.addColumn("MB");
        modelTabelBasisPengetahuan.addColumn("MD");
        tampilDataBasisPengetahuan();
    }
    
    
    public void tampilDataBasisPengetahuan() {
        try {
            modelTabelBasisPengetahuan.getDataVector().removeAllElements();
            modelTabelBasisPengetahuan.fireTableDataChanged();
            
            PreparedStatement query = obj.konek.prepareStatement("SELECT * FROM basis_pengetahuan");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] line = new Object[5];
                line[0] = data.getString("kode_pengetahuan");
                line[1] = data.getString("kode_penyakit");
                line[2] = data.getString("kode_gejala");
                line[3] = data.getString("mb");
                line[4] = data.getString("md");
                modelTabelBasisPengetahuan.addRow(line);   
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKdPengetahuan = new javax.swing.JTextField();
        txtKdPenyakit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKdGejala = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBasisPengetahuan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Pengetahuan");

        txtKdPengetahuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdPengetahuanActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode Penyakit");

        jLabel3.setText("Kode Gejala");

        jLabel4.setText("mb");

        jLabel5.setText("md");

        jButton1.setText("Simpan Statement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan Prepare Statement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tableBasisPengetahuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBasisPengetahuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBasisPengetahuanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBasisPengetahuan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtKdGejala, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtKdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtKdPengetahuan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMd, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKdPengetahuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtKdGejala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKdPengetahuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdPengetahuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKdPengetahuanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
           if (txtKdPengetahuan.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Pengetahuan belum di isi");
               txtKdPengetahuan.requestFocus();
           } else if (txtKdPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Penyakit belum diisi");
               txtKdPenyakit.requestFocus();
           } else if (txtKdGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Gejala belum diisi");
               txtKdGejala.requestFocus();
           } else if (txtMb.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "MB belum diisi");
               txtMb.requestFocus();
           } else if (txtMd.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "MD belum diisi");
               txtMd.requestFocus();
           } else {
               String sql = "insert into basis_pengetahuan value('"+txtKdPengetahuan.getText()+"','"+txtKdPenyakit.getText()+"','"+txtKdGejala.getText()+"','"+txtMb.getText()+"','"+txtMd.getText()+"')";
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
           if (txtKdPengetahuan.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode pengetahuan belum di isi");
               txtKdPengetahuan.requestFocus();
           } else if (txtKdPenyakit.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode penyakit belum diisi");
               txtKdPenyakit.requestFocus();
           } else if (txtKdGejala.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Kode gejala belum diisi");
               txtKdGejala.requestFocus();
           } else if (txtMb.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Mb belum diisi");
               txtMb.requestFocus();
           } else if (txtMd.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Md belum diisi");
               txtMd.requestFocus();
           } else {
               String sqlCari = "SELECT * FROM basis_pengetahuan WHERE kode_pengetahuan ='"+txtKdPengetahuan.getText()+"'";
               ResultSet cari = obj.konek.createStatement().executeQuery(sqlCari);
               if (cari.next()){
                    JOptionPane.showMessageDialog(this, "NPM Sudah Terdaftar");
                         txtKdPenyakit.setText(cari.getString(2));
                         txtKdGejala.setText(cari.getString(3));
                         txtMb.setText(cari.getString(4));
                         txtMd.setText(cari.getString(5));
               } else {
                    String sql = "INSERT INTO basis_pengetahuan VALUE(?, ?, ?, ?, ?)";
                    PreparedStatement simpan = obj.konek.prepareStatement(sql);
                    simpan.setString(1, txtKdPengetahuan.getText());
                    simpan.setString(2, txtKdPenyakit.getText());
                    simpan.setString(3, txtKdGejala.getText());
                    simpan.setString(4, txtMb.getText());
                    simpan.setString(5, txtMd.getText());
                    simpan.executeUpdate();
                    tampilDataBasisPengetahuan();
                    
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
               }
         
               
               
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableBasisPengetahuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBasisPengetahuanMouseClicked
        // TODO add your handling code here:
        int baris = tableBasisPengetahuan.getSelectedRow();
        String kode_pengetahuan = tableBasisPengetahuan.getValueAt(baris, 0).toString();
        String kode_penyakit = tableBasisPengetahuan.getValueAt(baris, 1).toString();
        String kode_gejala = tableBasisPengetahuan.getValueAt(baris, 2).toString();
        String mb = tableBasisPengetahuan.getValueAt(baris, 3).toString();
        String md = tableBasisPengetahuan.getValueAt(baris, 4).toString();
        txtKdPengetahuan.setText(kode_pengetahuan);
        txtKdPenyakit.setText(kode_penyakit);
        txtKdGejala.setText(kode_gejala);
        txtMb.setText(mb);
        txtMd.setText(md);
    }//GEN-LAST:event_tableBasisPengetahuanMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
            if (
                    (txtKdPengetahuan.getText().isEmpty()) &&
                    (txtKdPenyakit.getText().isEmpty()) &&
                    (txtKdGejala.getText().isEmpty()) &&
                    (txtMb.getText().isEmpty()) &&
                    (txtMd.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "UPDATE basis_pengetahuan SET kode_penyakit=?, kode_gejala=?, mb=?, md=?  WHERE kode_pengetahuan=?";
                PreparedStatement ubah = obj.konek.prepareStatement(sql);
                ubah.setString(1, txtKdPenyakit.getText());
                ubah.setString(2, txtKdGejala.getText());
                ubah.setString(3, txtMb.getText());
                ubah.setString(4, txtMd.getText());
                ubah.setString(5, txtKdPengetahuan.getText());
                ubah.executeUpdate();
                tampilDataBasisPengetahuan();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try {
            if (
                    (txtKdPengetahuan.getText().isEmpty()) &&
                    (txtKdPenyakit.getText().isEmpty()) &&
                    (txtKdGejala.getText().isEmpty()) &&
                    (txtMb.getText().isEmpty()) &&
                    (txtMd.getText().isEmpty())
               ) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
            } else {
                String sql= "DELETE FROM basis_pengetahuan WHERE kode_pengetahuan=?";
                PreparedStatement hapus = obj.konek.prepareStatement(sql);
                hapus.setString(1, txtKdPengetahuan.getText());
                hapus.executeUpdate();
                tampilDataBasisPengetahuan();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameBasisPengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameBasisPengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameBasisPengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameBasisPengetahuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameBasisPengetahuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBasisPengetahuan;
    private javax.swing.JTextField txtKdGejala;
    private javax.swing.JTextField txtKdPengetahuan;
    private javax.swing.JTextField txtKdPenyakit;
    private javax.swing.JTextField txtMb;
    private javax.swing.JTextField txtMd;
    // End of variables declaration//GEN-END:variables
}
